# Generated by Django 3.2.6 on 2021-12-11 21:18

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='link',
            field=models.ManyToManyField(default=django.contrib.auth.models.User, related_name='links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Link',
        ),
    ]
