# Generated by Django 3.2.6 on 2021-12-12 11:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0004_auto_20211211_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='link',
        ),
        migrations.AddField(
            model_name='block',
            name='user',
            field=models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
